       IDENTIFICATION DIVISION.
       PROGRAM-ID. BENCH-ACCOUNT-BALANCE.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 WS-OPENING-BALANCE      PIC S9(9)V99 COMP-3 VALUE 0.
       01 WS-TRANSACTION-AMOUNT   PIC S9(9)V99 COMP-3 VALUE 0.
       01 WS-RUNNING-BALANCE      PIC S9(9)V99 COMP-3 VALUE 0.
       01 WS-INTEREST-RATE        PIC 9V9(4) COMP-3 VALUE 0.035.
       01 WS-INTEREST-EARNED      PIC S9(9)V99 COMP-3 VALUE 0.
       01 WS-NEW-BALANCE          PIC S9(9)V99 COMP-3 VALUE 0.
       01 WS-COUNTER              PIC 9(7) VALUE 0.
       PROCEDURE DIVISION.
       MAIN-PARA.
           MOVE 100000 TO WS-OPENING-BALANCE
           MOVE 50000  TO WS-TRANSACTION-AMOUNT
           PERFORM 1000000 TIMES
               ADD WS-TRANSACTION-AMOUNT TO WS-OPENING-BALANCE
                   GIVING WS-RUNNING-BALANCE
               COMPUTE WS-INTEREST-EARNED =
                   WS-RUNNING-BALANCE * WS-INTEREST-RATE
               COMPUTE WS-NEW-BALANCE =
                   WS-RUNNING-BALANCE + WS-INTEREST-EARNED
           END-PERFORM
           STOP RUN.
