       IDENTIFICATION DIVISION.
       PROGRAM-ID. BENCH-REPORT.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 WS-AMOUNT   PIC S9(9)V99 COMP-3 VALUE 150000.
       01 WS-BALANCE  PIC S9(9)V99 COMP-3 VALUE 155250.
       01 WS-BAL-DISP PIC Z(9).99.
       01 WS-LINE     PIC X(80) VALUE SPACES.
       PROCEDURE DIVISION.
       MAIN-PARA.
           PERFORM 1000000 TIMES
               MOVE SPACES TO WS-LINE
               MOVE WS-BALANCE TO WS-BAL-DISP
               STRING 'Account: ' DELIMITED SIZE
                      WS-BAL-DISP DELIMITED SIZE
                      INTO WS-LINE
           END-PERFORM
           STOP RUN.
