       IDENTIFICATION DIVISION.
       PROGRAM-ID. BENCH-BATCH.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 WS-TOTAL-CREDITS        PIC S9(11)V99 COMP-3 VALUE 0.
       01 WS-TOTAL-DEBITS         PIC S9(11)V99 COMP-3 VALUE 0.
       01 WS-TRANSACTION-AMOUNT   PIC S9(9)V99 COMP-3 VALUE 0.
       01 WS-NET-POSITION         PIC S9(11)V99 COMP-3 VALUE 0.
       01 WS-TRANSACTION-TYPE     PIC X VALUE 'C'.
       PROCEDURE DIVISION.
       MAIN-PARA.
           MOVE 100000 TO WS-TRANSACTION-AMOUNT
           PERFORM 1000000 TIMES
               IF WS-TRANSACTION-TYPE = 'C'
                   ADD WS-TRANSACTION-AMOUNT TO WS-TOTAL-CREDITS
               ELSE
                   ADD WS-TRANSACTION-AMOUNT TO WS-TOTAL-DEBITS
               END-IF
               COMPUTE WS-NET-POSITION =
                   WS-TOTAL-CREDITS - WS-TOTAL-DEBITS
           END-PERFORM
           STOP RUN.
